//! App icon — embedded PNG shown in the native window title bar / taskbar.
//!
//! The asset is generated by `scripts/design_icon.py` (Pillow). `include_bytes!`
//! bakes the PNG straight into the binary so the icon works without shipping an
//! external file. Sizes 16…1024 plus a Windows `.ico` live in `assets/icon/`.
//!
//! > **`.exe` 파일 자체의 아이콘**(바탕화면/탐색기 파일 아이콘 · 작업 관리자
//! > 프로세스 아이콘)은 여기가 아니라 `build.rs` + `win/app.rc`가 빌드 타임에
//! > `app_icon.ico`를 PE 리소스로 임베드해서 담당합니다 — 런타임 API 불필요.

/// 512 px RGBA PNG — good compromise between taskbar crispness (HiDPI) and size.
pub const APP_ICON_PNG: &[u8] = include_bytes!("../assets/icon/app_icon.png");