//! App icon — embedded PNG shown in the native window title bar / taskbar.
//!
//! The asset is generated by `scripts/design_icon.py` (Pillow). `include_bytes!`
//! bakes the PNG straight into the binary so the icon works without shipping an
//! external file. Sizes 16…1024 plus a Windows `.ico` live in `assets/icon/`.

/// 512 px RGBA PNG — good compromise between taskbar crispness (HiDPI) and size.
pub const APP_ICON_PNG: &[u8] = include_bytes!("../assets/icon/app_icon.png");